### ISSUE TITLE
See an illegal instruction error when I try to call the Train() API over an IVF100,SQ8 index built using IndexFactory(..)

### ISSUE THREAD

**Issue by abhinavdangeti** [DataIntelligenceCrew/go-faiss#23]
I've built and installed FAISS per instructions on my ubuntu system. Has anyone seen anything of the likes or any pointers on how this could happen?

```
SIGILL: illegal instruction
--
PC=0x7fc8901c2cae m=8 sigcode=2
signal arrived during cgo execution
instruction bytes: 0xc5 0xfa 0x10 0x0 0x48 0x8b 0x85 0x60 0xff 0xff 0xff 0x8b 0x0 0x4c 0x8b 0x45goroutine 1122 [syscall]:
runtime.cgocall(0x124f1f0, 0xc000b55108)
/home/couchbase/.cbdepscache/exploded/x86_64/go-1.21.3/go/src/runtime/cgocall.go:157 +0x4b fp=0xc000b550e0 sp=0xc000b550a8 pc=0x40b70b
github.com/blevesearch/go-faiss._Cfunc_faiss_Index_train(0x7fc81ccdd400, 0x2ed2, 0xc00e2e0000)
_cgo_gotypes.go:513 +0x4b fp=0xc000b55108 sp=0xc000b550e0 pc=0x6e722b
github.com/blevesearch/go-faiss.(*faissIndex).Train.func1(0x7fc81ccdd400?, 0x2?, {0xc00e2e0000, 0x43dcbb?, 0x7fc81ccdd3e0?})
..
```
The compiler on the system -
```
gcc (Ubuntu 9.4.0-1ubuntu1~20.04.2) 9.4.0
--
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by metonymic-smokey** [comment]
To add on to @abhinavdangeti's point, the CPU is an Intel(R) Xeon(R) Gold 6338N.
Details about the CPU instruction set supported are:
```
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush acpi mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl cpuid pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch cpuid_fault invpcid_single pti ssbd ibrs ibpb stibp fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm rdseed adx smap clflushopt clwb sha_ni xsaveopt xsavec xgetbv1 xsaves umip pku ospke gfni vaes vpclmulqdq rdpid md_clear flush_l1d
```
avx,avx2,sse4_2, the usual suspects in such issues, are supported.

Please let me know if you require any further info we could provide, thanks!

**Comment by p-ouellette** [comment]
I think you'll have better luck if you report this to faiss upstream (assuming this is reproducible in C/C++).
